export const permissionKeys = [
  "departments.create",
  "departments.update",
  "departments.delete",
  "departments.view",
  "users.create",
  "users.update",
  "users.deactivate",
  "users.assign_role",
  "roles.create",
  "roles.update",
  "roles.delete",
  "roles.assign_permissions",
  "leave.request",
  "leave.view_own",
  "leave.view_department",
  "leave.approve",
  "leave.reject",
  "shifts.view_own",
  "shifts.view_department",
  "shifts.create",
  "shifts.update",
  "shifts.cancel",
  "shifts.assign_employee",
  "tasks.view_own",
  "tasks.view_department",
  "tasks.create",
  "tasks.update",
  "tasks.delete",
  "tasks.assign",
] as const;

export type PermissionKey = (typeof permissionKeys)[number];
